"""empty message

Revision ID: 12dfa5289f7b
Revises: 29fcb79ff1b1
Create Date: 2021-03-29 07:53:49.769258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12dfa5289f7b'
down_revision = '29fcb79ff1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyname', sa.String(length=64), nullable=True),
    sa.Column('stockcode', sa.String(length=64), nullable=True),
    sa.Column('ipodate', sa.DateTime(), nullable=True),
    sa.Column('ipotype', sa.String(length=40), nullable=True),
    sa.Column('stocktype', sa.String(length=40), nullable=True),
    sa.Column('bankers', sa.String(length=64), nullable=True),
    sa.Column('bookvalue', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('stock_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyname', sa.String(length=64), nullable=True),
    sa.Column('stockcode', sa.String(length=64), nullable=True),
    sa.Column('ipodate', sa.DateTime(), nullable=True),
    sa.Column('ipotype', sa.String(length=40), nullable=True),
    sa.Column('stocktype', sa.String(length=40), nullable=True),
    sa.Column('bankers', sa.String(length=64), nullable=True),
    sa.Column('bookvalue', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('stock_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('companyname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('stockcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('ipodate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ipotype', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('stocktype', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('bankers', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('bookvalue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_table('user')
    op.drop_table('stock')
    # ### end Alembic commands ###
